spring.application.name=Layover_Backend

# 서버
server.port=8080

# DB 자동설정 끄기 (DB 확정 전까지 임시)
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.orm.jpa.autoconfigure.HibernateJpaAutoConfiguration

# 인코딩
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# JPA - camelCase(Java) -> snake_case(DB) 자동 변환
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JSON - camelCase 유지 (Vue와 통신할 때)
spring.jackson.property-naming-strategy=LOWER_CAMEL_CASE

# JWT
ssafy.jwt.access-expmin=60
ssafy.jwt.refresh-expmin=1440
ssafy.jwt.secret-string=layover-very-long-and-secure-random-secret-key-12345678